### ISSUE TITLE
Invalid Mail account data error

### ISSUE THREAD

**Issue by ghost** [baronleonardo/mailchecker#13]
"Invalid Mail account data error" kol shwaya, even though my mail account data is correct... it's just that there was no internet.

it needs to tell the difference, and doesn't check and give me an error kol shwaya when there is no internet.
![screenshot from 2015-06-17 15-40-11](https://cloud.githubusercontent.com/assets/6195060/8216453/f039b822-1536-11e5-836e-9d886ef87b11.png)

**Comment by baronleonardo** [comment]
Solved

**Comment by ghost** [comment]
good job... I ceased being a developer and I became a beta tester :'D
treat your beta tester as your most valuable asset and they will become your most valuable asset :D
