### ISSUE TITLE
Invalid Mail account data error when it's just no internet connection

### ISSUE THREAD

**Issue by ghost** [baronleonardo/mailchecker#14]
well, it doesn't notify me multiple times now, which is good.
but it gives me the wrong error message!
I don't even need to be notified anything when there is no internet.

**Comment by baronleonardo** [comment]
I will put this issue in the to-do list
I will keep this issue opened until it is solved

**Comment by ghost** [comment]
it has been fixed.
but now no icon is displayed when the program starts with no internet connection.

![screenshot from 2015-06-20 17-47-51](https://cloud.githubusercontent.com/assets/6195060/8267975/e978f35a-1774-11e5-853b-3a32e41d43eb.png)

**Comment by baronleonardo** [comment]
pull the new changes
start run the mail checker using the bash script
----------------------------------------------
This error happens due to the relative/absolute path and it have been handled by this script

**Comment by baronleonardo** [comment]
run the bash script "mail_checker"
