### ISSUE TITLE
when I hibernate and restore the icons are gone

### ISSUE THREAD

**Issue by ghost** [baronleonardo/mailchecker#15]
![screenshot from 2015-06-25 17-38-29](https://cloud.githubusercontent.com/assets/6195060/8359210/34bfda4c-1b65-11e5-95cc-e414f66709c5.png)

**Comment by baronleonardo** [comment]
Is it functional but just the icons disappear ?

**Comment by ghost** [comment]
yes it functions perfectly but the icon is gone

**Comment by baronleonardo** [comment]
did you run it from the mail_checker script ?
if so could you please paste the log after resume from sleep

**Comment by ghost** [comment]
what log?

**Comment by baronleonardo** [comment]
when you run it in a terminal, a log (bunch of sentences) appears as the app runs

**Comment by ghost** [comment]
alright will paste the log once the issue reoccures

**Comment by ghost** [comment]
I'm having a very hard time trying to reproduce the error. but I've just discovered that the .desktop file that I created for the app calls the python file instead of the shell script... so I've modified that and I'll consider the issue closed unless it occurs again.
