### ISSUE TITLE
I suppose there is support for multiple accounts but...

### ISSUE THREAD

**Issue by ghost** [baronleonardo/mailchecker#16]
when I try to add a new account the add button doesn't work.

**Comment by ghost** [comment]
should I pull the gtk3 branch or what?

**Comment by baronleonardo** [comment]
could you paste here the log ?

**Comment by ghost** [comment]
it's the normal log... it seems that you haven't pushed the latest updates to your master branch.
the only thing changed is the README.md

**Comment by baronleonardo** [comment]
you seemed you didn't pull the latest updates ^_^
check again

**Comment by ghost** [comment]
shut up :D

**Comment by ghost** [comment]
you may close that issue :D
