### ISSUE TITLE
A lot of our GTK widgets are deprecated

### ISSUE THREAD

**Issue by ghost** [baronleonardo/mailchecker#19]
`/home/adam/Workspace/mailchecker/settings_ui.py:59: Warning: The property GtkWidget:margin-left is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.builder.add_from_file(current_path + glade_file)
/home/adam/Workspace/mailchecker/settings_ui.py:59: Warning: The property GtkWidget:margin-right is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.builder.add_from_file(current_path + glade_file)
/home/adam/Workspace/mailchecker/settings_ui.py:59: Warning: The property GtkTreeView:rules-hint is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.builder.add_from_file(current_path + glade_file)
/home/adam/Workspace/mailchecker/settings_ui.py:59: Warning: The property GtkAlignment:top-padding is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.builder.add_from_file(current_path + glade_file)
/home/adam/Workspace/mailchecker/settings_ui.py:59: Warning: The property GtkAlignment:left-padding is deprecated and shouldn't be used anymore. It will be removed in a future version.`
are we gonna do something about it?

**Comment by baronleonardo** [comment]
this is not easy
but we will figure out a solution
