### ISSUE TITLE
when I add a new account, it holds the name of the previous one in the treeview

### ISSUE THREAD

**Issue by ghost** [baronleonardo/mailchecker#20]
![screenshot from 2015-07-10 03-24-18](https://cloud.githubusercontent.com/assets/6195060/8610618/cd89c88c-26b4-11e5-9590-1977ca88d09a.png)

![screenshot from 2015-07-10 03-25-19](https://cloud.githubusercontent.com/assets/6195060/8610626/e0639550-26b4-11e5-8c70-75732349ceaf.png)

**Comment by ghost** [comment]
it works correctly bas it holds the name of the previous email until I close and reopen the settings

**Comment by ghost** [comment]
![screenshot from 2015-07-10 03-43-45](https://cloud.githubusercontent.com/assets/6195060/8610698/f6b0c070-26b5-11e5-8802-ce7fce1e2024.png)

same issue occurs when editing.

**Comment by baronleonardo** [comment]
because in the database .. the email is "unique" part .. can not be added to the database .. so the methods that run after adding new mail .. not functional .. we just need a simple method that check availability of the same mail in out mail list

**Comment by baronleonardo** [comment]
Solved
