### ISSUE TITLE
invalid email has been accepted and added

### ISSUE THREAD

**Issue by ghost** [baronleonardo/mailchecker#21]
![screenshot from 2015-07-10 03-25-19](https://cloud.githubusercontent.com/assets/6195060/8610634/0deee0b0-26b5-11e5-8ea3-d8fd3a89655f.png)

I think we should check on the credentials first before we add it.

**Comment by baronleonardo** [comment]
it checks after we press save .. not on the fly .. it's more simple

**Comment by ghost** [comment]
When we press save, it adds it to the list anyway whether it is valid or invalid.
I don't think it's supposed to add it if it's invalid.

**Comment by baronleonardo** [comment]
this is another issue re open new one .. as this one has been closed

**Comment by lordadamson** [comment]
You can reopen it ya 3am

**Comment by baronleonardo** [comment]
the notifications/tooltip systems are handling this situation
