### ISSUE TITLE
which of my emails is invalid?

### ISSUE THREAD

**Issue by ghost** [baronleonardo/mailchecker#22]
![screenshot from 2015-07-10 03-25-43](https://cloud.githubusercontent.com/assets/6195060/8610648/3cedadd8-26b5-11e5-8958-9c1999de3a1c.png)

thanks for notifying me about the invalid data, but which one of my three emails is fault?

**Comment by baronleonardo** [comment]
Next commits will reconstruct some parts related to notifications/tooltips

**Comment by baronleonardo** [comment]
if you hover to the tray icon .. it will list the mail accounts statutes
