### ISSUE TITLE
adding second account just duplicates the first one

### ISSUE THREAD

**Issue by ghost** [baronleonardo/mailchecker#24]
![screenshot from 2015-09-14 01-24-53](https://cloud.githubusercontent.com/assets/6195060/9839611/e3829cbe-5a7f-11e5-8063-f36bca0e85fc.png)

I fill in the info for another account but it only just duplicated the first account and ignored my imput.

**Comment by ghost** [comment]
man, I love you, it finally works as expected :D :D

**Comment by baronleonardo** [comment]
you welcome man :D
