### ISSUE TITLE
enhancement: open particular mail when clicked on its notification

### ISSUE THREAD

**Issue by ghost** [baronleonardo/mailchecker#25]
![screenshot from 2015-09-19 23-06-59](https://cloud.githubusercontent.com/assets/6195060/9978188/792c9c72-5f23-11e5-8975-b3a061600cf4.png)
right now when I click on the mail checker icon it opens my browser to mail.google.com.
it would be absolutely perfect if I could click on the hotmail notification to open hotmail in my browser and click on google to open gmail in my browser.

so to sum this up: I want a custom command for each notification.

**Comment by baronleonardo** [comment]
it is pointless .. you can use mail manager for all of your accounts .. and just one click on the tray icon to open that app

check something like geary - A mac like mail manager -

**Comment by ghost** [comment]
I don't want to use a mail manager :(

**Comment by baronleonardo** [comment]
I'm sorry .. but that mean reconstruction in many parts of the program and it will takes long time.
