### ISSUE TITLE
it says "basics 1 new notification" at the lock screen

### ISSUE THREAD

**Issue by ghost** [baronleonardo/mailchecker#26]
![dsc_0198](https://cloud.githubusercontent.com/assets/6195060/10000180/e13d42da-609a-11e5-8315-d9a82c7b0ccf.JPG)

that's not meaningful at all.
I remember that it was me who put the word basics somewhere :D

**Comment by ghost** [comment]
I made a pull request to fix it

**Comment by baronleonardo** [comment]
done
